// <auto-generated />
using CampusBuzzAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusBuzzAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410055940_AddMoreEvents")]
    partial class AddMoreEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusBuzzAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventTitle = "Hackathon ",
                            Location = "IT Building",
                            TicketPrice = "Free"
                        },
                        new
                        {
                            Id = 2,
                            EventTitle = "UP Ovuwa",
                            Location = "Amphitheatre",
                            TicketPrice = "R120"
                        },
                        new
                        {
                            Id = 3,
                            EventTitle = "Tuks Camarata",
                            Location = "Auditorium",
                            TicketPrice = "R250"
                        },
                        new
                        {
                            Id = 4,
                            EventTitle = "Career Fair",
                            Location = "Main Hall",
                            TicketPrice = "Free"
                        },
                        new
                        {
                            Id = 5,
                            EventTitle = "150 Years of Tuks",
                            Location = "Hatfield Campus",
                            TicketPrice = "R80"
                        },
                        new
                        {
                            Id = 6,
                            EventTitle = "Sports Day",
                            Location = "LC",
                            TicketPrice = "R30"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
